//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanEMICalculator.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LoanEMICalculatorEntities : DbContext
    {
        public LoanEMICalculatorEntities()
            : base("name=LoanEMICalculatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblLoanCriteria> tblLoanCriterias { get; set; }
        public virtual DbSet<tblLoanEMITransaction> tblLoanEMITransactions { get; set; }
    }
}
