//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoanEMICalculator.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanEMITransaction
    {
        public int LoanEMITransID { get; set; }
        public int LoanCriteriaID { get; set; }
        public int InstallmentNo { get; set; }
        public double Opening { get; set; }
        public double Principle { get; set; }
        public double Interest { get; set; }
        public double EMI { get; set; }
        public double Closing { get; set; }
        public double CummulativeInterest { get; set; }
    
        public virtual tblLoanCriteria tblLoanCriteria { get; set; }
    }
}
